---
- name: Install tuned demon and add to systemd
  hosts: my
  become: yes

  tasks:

    - name: Install tuned demon
      package: # Означает, что нужно установить пакет tuned
        name: tuned
        state: present # Указывает, что пакет должен быть установлен (present)

    - name: Enable and start tuned service
      systemd: # Модуль для управления системными службами
        name: tuned # Имя службы, которую нужно управлять
        enabled: yes # Указывает, что служба должна быть включена при загрузке системы
        state: started # Указывает, что служба должна быть запущена