---
- name: Dowload and open archive
  hosts: my
  become: yes

  tasks:

    - name: Create directory for archive
      file:
        path: "/tmp/kafka"
        state: directory
        mode: '0755'


    - name: Download archive
      get_url:
        url: "https://www.apache.org/dyn/closer.lua/kafka/4.3.0/kafka_2.13-4.3.0.tgz?action=download"
        dest: "/tmp/kafka/kafka_2.13-4.3.0.tgz"


    - name: Unarchive the downloaded file
      unarchive:
        src: "/tmp/kafka/kafka_2.13-4.3.0.tgz"
        dest: "/tmp/kafka"
        remote_src: yes
        creates: "/tmp/kafka/kafka_2.13-4.3.0"
