---
- name: Install tuned demon
  hosts: my
  become: yes

  tasks:

    - name: Install tuned demon
      package:
        name: tuned
        state: present

    - name: Enable and start tuned service
      systemd:
        name: tuned
        enabled: yes
        state: started